### PR TITLE
Add papis to bibliography tools

### PR DESCRIPTION
**Pull request by alejandrogallo**
I have added the program papis to the bibliography tools.
It is a real alternative to zotero or mendeley.

Warning: I am the main developer.

### CODE REVIEW

**Comment by egeerardyn** [comment]
Thank you for your contribution and being up-front about being the main developer.

I think from the description it really looks like a cool project (if I were still in academia, I would probably give it a whirl). 

Unfortunately, I feel papis might still be a bit too young to include in this list (no pull requests, no issues yet, only a single dev, version 0.1.2, only a few users as far as I can see, ...).

**Comment by alejandrogallo** [comment]
Sure no worries. It is stable enough but it is certainly true that there is a quite small
user group and that it is young. It is however very stable but I have to work harder
in advertising it to other people, that is why I tried this out, I might therefore try further in the future ;)

Thanks for your fast reply, you might close this pull request if you wish!

PD: You can also use it for books, managing contacts, videos, etc.. etc..

**Comment by egeerardyn** [comment]
I completely understand, and know how it feels to try to get a nice project up and running with a lot of users (it is not easy).
You might want to try writing a blog post or try contacting some TeX user groups to get the initial momentum.

I can't judge the stability of papis (but if you are using it on a daily basis, I can imagine it should be stable). I am quite convinced that in a few weeks/months, I may be more inclined to include it here as well :-)

**Comment by alejandrogallo** [comment]
Hi! Any chance this would be reviewed? `papis` grew quite  a lot in these months, we got new users, more devs and even a review. [link](https://github.com/alejandrogallo/papis) Cheers!

**Comment by koppor** [comment]
@alejandrogallo Maybe you can add your tool to the ultimate reference management software comparison: https://ultimate-comparisons.github.io/ultimate-reference-management-software-comparison/. Just create a new file at https://github.com/ultimate-comparisons/ultimate-reference-management-software-comparison/tree/master/comparison-elements. Use https://github.com/ultimate-comparisons/ultimate-reference-management-software-comparison/blob/master/comparison-elements/template.md as basis.

**Comment by alejandrogallo** [comment]
Thanks @koppor , I will do just that!

**Comment by alejandrogallo** [comment]
Great! Thanks!

**Pull request merged**
