### PR TITLE
Add CaTeX

### PR DESCRIPTION
**Pull request by Alexis-benoist**

### CODE REVIEW

**Comment by egeerardyn** [comment]
I don't immediately see what you gain from using `catex` instead of just `cat` (on Unix systems).

That should be clarified:
 - in the description of the `CaTeX` entry here, and
 - while you are at it, on your project page as well.

For the latter, I would even suggest to add what use case you have in mind for this utility, what it does differently than just `cat` (and what is beyond the scope of that utility).

Also, I would have preferred you  explicitly mentioning that you are the developer of `catex` in this PR; as indicated in the contribution guidelines:
> Self-promotion can be okay, but *only* if you clearly state your involvement.

**Comment by Alexis-benoist** [comment]
Hey,
Sorry for the long response time.
You're right, I'm working on it, not hiding anything :)
Thanks for the detailed reply.

### The use case:
You're doing a PhD and have some articles, you want to merge them into your thesis. It can be used to "prototype" your thesis.

### What it does:
`CaTeX` contatenates the contents of the articles, merges the fields author and title and the packages.

Do you find it clear?

**Comment by egeerardyn** [comment]
Not completely. I see the use case, but the details of what is happening is not completely clear yet.
Am I correct in thinking that this:
 - merges the preambles (i.e. if you load e.g. `amsmath` in both, it only gets loaded once in the result; it merges the author list, ...);
 - concatenates the actual bodies of the documents (i.e. anything in the `document` environment)?

Or is there more (or less) magic happening? E.g.
-  just dumb concatenation of the preambles; 
- also taking into account that some packages (e.g. hyperref, ...) should be loaded before/after some other packages, ...
- also taking into account that multiple `\newlength`, `\newcommand` statements can conflict, ...
- some document classes (e.g. report vs article, IEEE vs article, ...) define new and incompatible commands, how does this get handled?

I think I am just a bit distrusting, because a lot can go wrong and I would like to know what the limitations are (that's just me personally). And I think that would make your project README also more accessible, if you can say: e.g. "usepackages are handled such and such, duplicate names in `\newcommand`s are not detected, ..." 

Once the description is more clear, I am more than happy to include it in the list. It's just right now, I want to understand (for myself personally), what I gain by using `CaTeX` over doing it manually (which I did for my PhD). My prejudice towards such automatic tools is that those will produce some output, but I will have to read all the output as well and correct for non-trivial stuff by hand (see above for some of those). And in that case, I might as well just merge by hand since I have to go over everything anyway. 

(Note that I don't want to imply your tool and work to be useless, I just want to make sure that you advertise more clearly what it does and what it does not do (yet?)).

**Comment by Alexis-benoist** [comment]
For the package list merging:

If a package is in only a doc merged, we just copy the line in the output.
If a package is in several docs, we put the package with all the options
(sorted and deduplicated).

We take the first author, title and document_class.

We concatenate all the non author, non title, non package and non
document_class of the preamble.

Of course, some things can go wrong (incompatible commands...).

It's good questions. I may find a bit of time for this module, but I'm not
really a user, so I don't really know what is expected. It can be improved
for sure.

Is it clearer?

2016-08-06 13:52 GMT+02:00 Egon Geerardyn <notifications@github.com>:

**Comment by egeerardyn** [comment]
This is indeed clearer. If you update the README in your repository and change it here to something like "Concatenates LaTeX documents with attention for properly merging the preamble" (or something similar), then I will gladly incorporate it!

**Comment by egeerardyn** [comment]
Sorry for the late response: 👍

**Pull request merged**
